name: epson_printer
description: A Flutter plugin for Epson printers.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  epson_printer_platform_interface:
    path: ../epson_printer_platform_interface
  epson_printer_ios:
    path: ../epson_printer_ios
  epson_printer_android:
    path: ../epson_printer_android

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        default_package: epson_printer_ios
      android:
        default_package: epson_printer_android